name: Flutter CI

on:
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test --no-pub

      - name: Check for test failures
        if: failure()
        run: |
          echo "Tests failed. PR cannot be merged."
          exit 1

# Ensure the flutter-version matches your pubspec.yaml SDK constraint (e.g., 3.7.2 or higher)
# Update the flutter-version above if you upgrade your Dart/Flutter SDK in pubspec.yaml
